const lilypond_spellings_modal = {
	"a_acoustic": "cs ds e fs g a b",
    "as_acoustic": "c d e f g af bf",
    "b_acoustic": "cs ds es fs gs a b",
    "c_acoustic": "c d e fs g a bf",
    "cs_acoustic": "cf df ef f g af bf",
    "d_acoustic": "c d e fs gs a b", 
    "ds_acoustic": "c df ef f g a bf",
    "e_acoustic": "cs d e fs gs as b",
    "f_acoustic": "c d ef f g a b",
    "fs_acoustic": "cs ds e fs gs as bs",
    "g_acoustic": "cs d e f g a b",
    "gs_acoustic": "c d ef f gf af bf",

    "a_diatonic": "cs d e fs gs a b", 
    "as_diatonic": "c d ef f g a bf",
    "b_diatonic": "cs ds e fs gs as b",
    "c_diatonic": "c d e f g a b",
    "cs_diatonic": "c df ef f gf af bf",
    "d_diatonic": "cs d e fs g a b",
    "ds_diatonic": "c d ef f g af bf ",
    "e_diatonic": "cs ds e fs gs a b",
    "f_diatonic": "c d e f g a bf",
    "fs_diatonic": "cs ds es fs gs as b",
    "g_diatonic": "c d e fs g a b",
    "gs_diatonic": "c df ef f g af bf",

    "a_harmonic_major": "cs d e f gs a b",
    "as_harmonic_major": "c d ef f gf a bf",
    "b_harmonic_major": "cs ds e fs g as b",
    "c_harmonic_major": "c d e f g af b",
    "cs_harmonic_major": "c df ef f gf af bff",
    "d_harmonic_major": "cs d e fs g a bf",
    "ds_harmonic_major": "cf d ef f g af bf",
    "e_harmonic_major": "c ds e fs gs a b",
    "f_harmonic_major": "c df e f g a bf",
    "fs_harmonic_major": "cs d es fs gs as b",
    "g_harmonic_major": "c d ef fs g a b",
    "gs_harmonic_major": "c df ef ff g af bf",

    "a_harmonic_minor": "c d e f gs a b",
    "as_harmonic_minor": "c df ef f gf a bf",
    "b_harmonic_minor": "cs d e fs g as b",
    "c_harmonic_minor": "c d ef f g af b",
    "cs_harmonic_minor": "c df ef ff gf af bff",
    "d_harmonic_minor": "cs d e f g a bf",
    "ds_harmonic_minor": "cf d ef f gf af bf",
    "e_harmonic_minor": "c ds e fs g a b",
    "f_harmonic_minor": "c df e f g af bf",
    "fs_harmonic_minor": "cs d es fs gs a b",
    "g_harmonic_minor": "c d ef fs g a bf",
    "gs_harmonic_minor": "cf df ef ff g af bf"
}

const solfege = {
    "a_acoustic": "di ri mi fi sol la ti",
    "as_acoustic": "do re mi fa sol le te",
    "b_acoustic": "di ri mai fi si la ti",
    "c_acoustic": "do re mi fi sol la te",
    "cs_acoustic": "de ra me fa sol le te",
    "d_acoustic": "do re mi fi si la ti", 
    "ds_acoustic": "do ra me fa sol la te",
    "e_acoustic": "di re mi fi si li ti",
    "f_acoustic": "do re me fa sol la ti",
    "fs_acoustic": "di ri mi fi si li tai",
    "g_acoustic": "di re mi fa sol la ti",
    "gs_acoustic": "do re me fa se le te",

    "a_diatonic": "di re mi fi si la ti", 
    "as_diatonic": "do re me fa sol la te",
    "b_diatonic": "di ri mi fi si li ti",
    "c_diatonic": "do re mi fa sol la ti",
    "cs_diatonic": "do ra me fa se le te",
    "d_diatonic": "di re mi fi sol la ti",
    "ds_diatonic": "do re me fa sol le ti",
    "e_diatonic": "di ri mi fi si la ti",
    "f_diatonic": "do re mi fa sol la te",
    "fs_diatonic": "di ri mai fi si li ti",
    "g_diatonic": "do re mi fi sol la ti",
    "gs_diatonic": "do ra me fa sol le te",

    "a_harmonic_major": "di re mi fa si la ti",
    "as_harmonic_major": "do re me fa se la te",
    "b_harmonic_major": "di ri mi fi sol li ti",
    "c_harmonic_major": "do re mi fa sol le ti",
    "cs_harmonic_major": "do ra me fa se le taw",
    "d_harmonic_major": "di re mi fi sol la te",
    "ds_harmonic_major": "de re me fa sol le te",
    "e_harmonic_major": "do ri mi fi si la ti",
    "f_harmonic_major": "do ra mi fa sol la te",
    "fs_harmonic_major": "di re mai fi si li ti",
    "g_harmonic_major": "do re me fi sol la ti",
    "gs_harmonic_major": "do ra me fe sol le te",

    "a_harmonic_minor": "do re mi fa si la ti",
    "as_harmonic_minor": "do ra me fa se la te",
    "b_harmonic_minor": "di re mi fi sol li ti",
    "c_harmonic_minor": "do re me fa sol le ti",
    "cs_harmonic_minor": "do ra me fe se le taw",
    "d_harmonic_minor": "di re mi fa sol la te",
    "ds_harmonic_minor": "de re me fa se le te",
    "e_harmonic_minor": "do ri mi fi sol la ti",
    "f_harmonic_minor": "do ra mi fa sol le te",
    "fs_harmonic_minor": "di re mai fi si la ti",
    "g_harmonic_minor": "do re me fi sol la te",
    "gs_harmonic_minor": "de ra me fe sol le te"
}
