const lilypond_spellings = {
    "a_acoustic": "cs ds e fs g a b",
    "as_acoustic": "c d e f g af bf",
    "b_acoustic": "cs ds es fs gs a b",
    "c_acoustic": "c d e fs g a bf",
    "cs_acoustic": "cf df ef f g af bf",
    "d_acoustic": "c d e fs gs a b", 
    "ds_acoustic": "c df ef f g a bf",
    "e_acoustic": "cs d e fs gs as b",
    "f_acoustic": "c d ef f g a b",
    "fs_acoustic": "cs ds e fs gs as bs",
    "g_acoustic": "cs d e f g a b",
    "gs_acoustic": "c d ef f gf af bf",

    "a_diatonic": "cs d e fs gs a b", 
    "as_diatonic": "c d ef f g a bf",
    "b_diatonic": "cs ds e fs gs as b",
    "c_diatonic": "c d e f g a b",
    "cs_diatonic": "c df ef f gf af bf",
    "d_diatonic": "cs d e fs g a b",
    "ds_diatonic": "c d ef f g af bf",
    "e_diatonic": "cs ds e fs gs a b",
    "f_diatonic": "c d e f g a bf",
    "fs_diatonic": "cs ds es fs gs as b",
    "g_diatonic": "c d e fs g a b",
    "gs_diatonic": "c df ef f g af bf",

    "a_harmonic_major": "cs d e f gs a b",
    "as_harmonic_major": "c d ef f gf a bf",
    "b_harmonic_major": "cs ds e fs g as b",
    "c_harmonic_major": "c d e f g af b",
    "cs_harmonic_major": "c df ef f gf af bff",
    "d_harmonic_major": "cs d e fs g a bf",
    "ds_harmonic_major": "cf d ef f g af bf",
    "e_harmonic_major": "c ds e fs gs a b",
    "f_harmonic_major": "c df e f g a bf",
    "fs_harmonic_major": "cs d es fs gs as b",
    "g_harmonic_major": "c d ef fs g a b",
    "gs_harmonic_major": "c df ef ff g af bf",

    "a_harmonic_minor": "c d e f gs a b",
    "as_harmonic_minor": "c df ef f gf a bf",
    "b_harmonic_minor": "cs d e fs g as b",
    "c_harmonic_minor": "c d ef f g af b",
    "cs_harmonic_minor": "c df ef ff gf af bff",
    "d_harmonic_minor": "cs d e f g a bf",
    "ds_harmonic_minor": "cf d ef f gf af bf",
    "e_harmonic_minor": "c ds e fs g a b",
    "f_harmonic_minor": "c df e f g af bf",
    "fs_harmonic_minor": "cs d es fs gs a b",
    "g_harmonic_minor": "c d ef fs g a bf",
    "gs_harmonic_minor": "cf df ef ff g af bf",

    "whole_tone_1": "c d e fs af bf",
    "whole_tone_2": "cs ef f g a b",

    "octatonic_1": "c cs ds e fs g a bf",
    "octatonic_2": "cs d e f g gs as b",
    "octatonic_3": "c d ef f fs gs a b",

    "hexatonic_1": "c df e f gs a",
    "hexatonic_2": "cs d f gf a as",
    "hexatonic_3": "d ef fs g as b",
    "hexatonic_4": "c ds e g gs b"
}

const detuned = {
        "a_acoustic": "as_acoustic",
    "as_acoustic": "b_acoustic",
    "b_acoustic": "c_acoustic",
    "c_acoustic": "cs_acoustic",
    "cs_acoustic": "d_acoustic",
    "d_acoustic": "ds_acoustic", 
    "ds_acoustic": "e_acoustic",
    "e_acoustic": "f_acoustic",
    "f_acoustic": "fs_acoustic",
    "fs_acoustic": "g_acoustic",
    "g_acoustic": "gs_acoustic",
    "gs_acoustic": "a_acoustic",

    "a_diatonic": "as_diatonic", 
    "as_diatonic": "b_diatonic",
    "b_diatonic": "c_diatonic",
    "c_diatonic": "cs_diatonic",
    "cs_diatonic": "d_diatonic",
    "d_diatonic": "ds_diatonic",
    "ds_diatonic": "e_diatonic",
    "e_diatonic": "f_diatonic",
    "f_diatonic": "fs_diatonic",
    "fs_diatonic": "g_diatonic",
    "g_diatonic": "gs_diatonic",
    "gs_diatonic": "a_diatonic",

    "a_harmonic_major": "as_harmonic_major",
    "as_harmonic_major": "b_harmonic_major",
    "b_harmonic_major": "c_harmonic_major",
    "c_harmonic_major": "cs_harmonic_major",
    "cs_harmonic_major": "d_harmonic_major",
    "d_harmonic_major": "ds_harmonic_major",
    "ds_harmonic_major": "e_harmonic_major",
    "e_harmonic_major": "f_harmonic_major",
    "f_harmonic_major": "fs_harmonic_major",
    "fs_harmonic_major": "g_harmonic_major",
    "g_harmonic_major": "gs_harmonic_major",
    "gs_harmonic_major": "a_harmonic_major",

    "a_harmonic_minor": "as_harmonic_minor",
    "as_harmonic_minor": "b_harmonic_minor",
    "b_harmonic_minor": "c_harmonic_minor",
    "c_harmonic_minor": "cs_harmonic_minor",
    "cs_harmonic_minor": "d_harmonic_minor",
    "d_harmonic_minor": "ds_harmonic_minor",
    "ds_harmonic_minor": "e_harmonic_minor",
    "e_harmonic_minor": "f_harmonic_minor",
    "f_harmonic_minor": "fs_harmonic_minor",
    "fs_harmonic_minor": "g_harmonic_minor",
    "g_harmonic_minor": "gs_harmonic_minor",
    "gs_harmonic_minor": "a_harmonic_minor",

    "whole_tone_1": "whole_tone_2",
    "whole_tone_2": "whole_tone_1",

    "octatonic_1": "octatonic_2",
    "octatonic_2": "octatonic_3",
    "octatonic_3": "octatonic_1",

    "hexatonic_1": "hexatonic_2",
    "hexatonic_2": "hexatonic_3",
    "hexatonic_3": "hexatonic_4",
    "hexatonic_4": "hexatonic_1"

}