const lilypond_spellings = {
	"a_acoustic": "a b cs' ds' e' fs' g'",
    "as_acoustic": "bf c' d' e' f' g' af'",
    "b_acoustic": "b cs' ds' es' fs' gs' a'",
    "c_acoustic": "c d e fs g a bf",
    "cs_acoustic": "df ef f g af bf cf'",
    "d_acoustic": "d e fs gs a b c'", 
    "ds_acoustic": "ef f g a bf c' df'",
    "e_acoustic": "e fs gs as b cs' d'",
    "f_acoustic": "f g a b c' d' ef'",
    "fs_acoustic": "fs gs as bs cs' ds' e'",
    "g_acoustic": "g a b cs' d' e' f'",
    "gs_acoustic": "af bf c' d' ef' f' gf'",

    "a_diatonic": "a b cs' d' e' fs' gs'", 
    "as_diatonic": "bf c' d' ef' f' g' a'",
    "b_diatonic": "b cs' ds' e' fs' gs' as'",
    "c_diatonic": "c d e f g a b",
    "cs_diatonic": "df ef f gf af bf c'",
    "d_diatonic": "d e fs g a b cs'",
    "ds_diatonic": "ef f g af bf c' d'",
    "e_diatonic": "e fs gs a b cs' ds'",
    "f_diatonic": "f g a bf c' d' e'",
    "fs_diatonic": "fs gs as b cs' ds' es'",
    "g_diatonic": "g a b c' d' e' fs'",
    "gs_diatonic": "af bf c' df' ef' f' g'",

    "a_harmonic_major": "a b cs' d' e' f' gs'",
    "as_harmonic_major": "bf c' d' ef' f' gf' a'",
    "b_harmonic_major": "b cs' ds' e' fs' g' as'",
    "c_harmonic_major": "c d e f g af b",
    "cs_harmonic_major": "cs ds es fs gs a bs",
    "d_harmonic_major": "d e fs g a bf cs'",
    "ds_harmonic_major": "ef f g af bf cf' d'",
    "e_harmonic_major": "e fs gs a b c' ds'",
    "f_harmonic_major": "f g a bf c' df' e'",
    "fs_harmonic_major": "fs gs as b cs' d' es'",
    "g_harmonic_major": "g a b c' d' ef' fs'",
    "gs_harmonic_major": "gs as b cs' ds' e' fss'",

    "a_harmonic_minor": "a b c' d' e' f' gs'",
    "as_harmonic_minor": "bf c' df' ef' f' gf' a'",
    "b_harmonic_minor": "b cs' d' e' fs' g' as'",
    "c_harmonic_minor": "c d ef f g af b",
    "cs_harmonic_minor": "cs ds e fs gs a bs",
    "d_harmonic_minor": "d e f g a bf cs'",
    "ds_harmonic_minor": "ef f gf af bf cf' d'",
    "e_harmonic_minor": "e fs g a b c' ds'",
    "f_harmonic_minor": "f g as bf c' df' e'",
    "fs_harmonic_minor": "fs gs a b cs' d' es'",
    "g_harmonic_minor": "g a bf c' d' ef' fs'",
    "gs_harmonic_minor": "gs as b cs' ds' e' fss'"
}