const metadata = 
{"_13#9-110": {"alteration": "TRUE",
               "inversion": 1,
               "notes": [58, 64, 69, 72, 75],
               "position": 2,
               "quality": "dominant_seventh"},
 "_13-100": {"alteration": "FALSE",
             "inversion": 1,
             "notes": [58, 64, 69, 74, 79],
             "position": 2,
             "quality": "dominant_seventh"},
 "_13-101": {"alteration": "FALSE",
             "inversion": 1,
             "notes": [58, 64, 69, 74, 79, 84],
             "position": 2,
             "quality": "dominant_seventh"},
 "_13-18": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 58, 64, 69],
            "position": 1,
            "quality": "dominant_seventh"},
 "_13-20": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 58, 64, 69, 74],
            "position": 1,
            "quality": "dominant_seventh"},
 "_13-53": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 52, 58, 62, 69],
            "position": 2,
            "quality": "dominant_seventh"},
 "_13-79": {"alteration": "FALSE",
            "inversion": 1,
            "notes": [52, 58, 62, 69, 72],
            "position": 1,
            "quality": "dominant_seventh"},
 "_13♭5(♭9)-66": {"alteration": "TRUE",
                  "inversion": 0,
                  "notes": [48, 52, 58, 61, 66, 69],
                  "position": 2,
                  "quality": "dominant_seventh"},
 "_13♭5-106": {"alteration": "TRUE",
               "inversion": 1,
               "notes": [58, 64, 69, 74, 78],
               "position": 2,
               "quality": "dominant_seventh"},
 "_13♭5-31": {"alteration": "TRUE",
              "inversion": 0,
              "notes": [48, 58, 64, 66, 69],
              "position": 1,
              "quality": "dominant_seventh"},
 "_13♭5-33": {"alteration": "TRUE",
              "inversion": 0,
              "notes": [48, 58, 64, 69, 73],
              "position": 1,
              "quality": "dominant_seventh"},
 "_13♭5-61": {"alteration": "TRUE",
              "inversion": 0,
              "notes": [48, 52, 58, 62, 66, 69],
              "position": 2,
              "quality": "dominant_seventh"},
 "_13♭5-85": {"alteration": "TRUE",
              "inversion": 1,
              "notes": [52, 58, 62, 66, 69],
              "position": 1,
              "quality": "dominant_seventh"},
 "_13♭9-108": {"alteration": "TRUE",
               "inversion": 1,
               "notes": [58, 64, 69, 73, 79],
               "position": 2,
               "quality": "dominant_seventh"},
 "_13♭9-63": {"alteration": "TRUE",
              "inversion": 0,
              "notes": [48, 52, 58, 61, 69],
              "position": 2,
              "quality": "dominant_seventh"},
 "_13♭9-87": {"alteration": "TRUE",
              "inversion": 1,
              "notes": [52, 58, 61, 69, 72],
              "position": 1,
              "quality": "dominant_seventh"},
 "_6-4": {"alteration": "FALSE",
          "inversion": 0,
          "notes": [48, 55, 64, 69],
          "position": 1,
          "quality": "major"},
 "_6/9-42": {"alteration": "FALSE",
             "inversion": 0,
             "notes": [48, 52, 57, 62, 67],
             "position": 2,
             "quality": "major"},
 "_6/9-5": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 55, 64, 69, 74],
            "position": 1,
            "quality": "major"},
 "_6/9-71": {"alteration": "FALSE",
             "inversion": 1,
             "notes": [52, 57, 62, 67, 72],
             "position": 1,
             "quality": "major"},
 "_7#5(#9)-111": {"alteration": "TRUE",
                  "inversion": 1,
                  "notes": [58, 64, 68, 72, 75],
                  "position": 2,
                  "quality": "dominant_seventh"},
 "_7#5(#9)-36": {"alteration": "TRUE",
                 "inversion": 0,
                 "notes": [48, 58, 64, 68, 75],
                 "position": 1,
                 "quality": "dominant_seventh"},
 "_7#5(#9)-69": {"alteration": "TRUE",
                 "inversion": 0,
                 "notes": [48, 52, 58, 63, 68],
                 "position": 2,
                 "quality": "dominant_seventh"},
 "_7#5(#9)-90": {"alteration": "TRUE",
                 "inversion": 1,
                 "notes": [52, 58, 63, 68, 72],
                 "position": 1,
                 "quality": "dominant_seventh"},
 "_7#5(♭9)-34": {"alteration": "TRUE",
                 "inversion": 0,
                 "notes": [48, 58, 61, 68, 73],
                 "position": 1,
                 "quality": "dominant_seventh"},
 "_7#5(♭9)-64": {"alteration": "TRUE",
                 "inversion": 0,
                 "notes": [48, 52, 58, 61, 68],
                 "position": 2,
                 "quality": "dominant_seventh"},
 "_7#5(♭9)-88": {"alteration": "TRUE",
                 "inversion": 1,
                 "notes": [52, 58, 61, 68, 72],
                 "position": 1,
                 "quality": "dominant_seventh"},
 "_7#5-105": {"alteration": "TRUE",
              "inversion": 1,
              "notes": [58, 64, 68, 72, 76],
              "position": 2,
              "quality": "dominant_seventh"},
 "_7#5-27": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 58, 64, 68],
             "position": 1,
             "quality": "dominant_seventh"},
 "_7#9-109": {"alteration": "TRUE",
              "inversion": 1,
              "notes": [58, 64, 67, 72, 75],
              "position": 2,
              "quality": "dominant_seventh"},
 "_7#9-35": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 58, 64, 67, 75],
             "position": 1,
             "quality": "dominant_seventh"},
 "_7#9-67": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 52, 58, 63],
             "position": 2,
             "quality": "dominant_seventh"},
 "_7#9-68": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 52, 58, 63, 67],
             "position": 2,
             "quality": "dominant_seventh"},
 "_7#9-89": {"alteration": "TRUE",
             "inversion": 1,
             "notes": [52, 58, 63, 67, 72],
             "position": 1,
             "quality": "dominant_seventh"},
 "_7-17": {"alteration": "FALSE",
           "inversion": 0,
           "notes": [48, 58, 64, 67],
           "position": 1,
           "quality": "dominant_seventh"},
 "_7-51": {"alteration": "FALSE",
           "inversion": 0,
           "notes": [48, 52, 58, 67],
           "position": 2,
           "quality": "dominant_seventh"},
 "_7-alt.-91": {"alteration": "TRUE",
                "inversion": 1,
                "notes": [52, 58, 63, 68, 73],
                "position": 1,
                "quality": "dominant_seventh"},
 "_7♭5-29": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 58, 64, 66],
             "position": 1,
             "quality": "dominant_seventh"},
 "_7♭9(♭5)-65": {"alteration": "TRUE",
                 "inversion": 0,
                 "notes": [48, 52, 58, 61, 66],
                 "position": 2,
                 "quality": "dominant_seventh"},
 "_7♭9-107": {"alteration": "TRUE",
              "inversion": 1,
              "notes": [58, 64, 67, 73, 79],
              "position": 2,
              "quality": "dominant_seventh"},
 "_7♭9-32": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 58, 64, 67, 73],
             "position": 1,
             "quality": "dominant_seventh"},
 "_7♭9-62": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 52, 58, 61, 67],
             "position": 2,
             "quality": "dominant_seventh"},
 "_7♭9-86": {"alteration": "TRUE",
             "inversion": 1,
             "notes": [52, 58, 61, 67, 72],
             "position": 1,
             "quality": "dominant_seventh"},
 "_9#5(♭5)-112": {"alteration": "TRUE",
                  "inversion": 1,
                  "notes": [58, 64, 68, 74, 78],
                  "position": 2,
                  "quality": "dominant_seventh"},
 "_9#5-28": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 58, 64, 68, 74],
             "position": 1,
             "quality": "dominant_seventh"},
 "_9#5-59": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 52, 58, 62, 68],
             "position": 2,
             "quality": "dominant_seventh"},
 "_9#5-83": {"alteration": "TRUE",
             "inversion": 1,
             "notes": [52, 58, 62, 68, 72],
             "position": 1,
             "quality": "dominant_seventh"},
 "_9-19": {"alteration": "FALSE",
           "inversion": 0,
           "notes": [48, 58, 64, 67, 74],
           "position": 1,
           "quality": "dominant_seventh"},
 "_9-52": {"alteration": "FALSE",
           "inversion": 0,
           "notes": [48, 52, 58, 62, 67],
           "position": 2,
           "quality": "dominant_seventh"},
 "_9-78": {"alteration": "FALSE",
           "inversion": 1,
           "notes": [52, 58, 62, 67, 72],
           "position": 1,
           "quality": "dominant_seventh"},
 "_9/11-99": {"alteration": "FALSE",
              "inversion": 1,
              "notes": [58, 63, 67, 74, 77],
              "position": 2,
              "quality": "minor"},
 "_9♭5-30": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 58, 64, 66, 74],
             "position": 1,
             "quality": "dominant_seventh"},
 "_9♭5-60": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 52, 58, 62, 66],
             "position": 2,
             "quality": "dominant_seventh"},
 "_9♭5-84": {"alteration": "TRUE",
             "inversion": 1,
             "notes": [52, 58, 62, 66, 72],
             "position": 1,
             "quality": "dominant_seventh"},
 "_M7#11-22": {"alteration": "TRUE",
               "inversion": 0,
               "notes": [48, 59, 64, 66],
               "position": 1,
               "quality": "major"},
 "_M7#11-55": {"alteration": "TRUE",
               "inversion": 0,
               "notes": [48, 52, 59, 62, 66],
               "position": 2,
               "quality": "major"},
 "_M7(add#11)-24": {"alteration": "TRUE",
                    "inversion": 0,
                    "notes": [48, 59, 64, 66, 74],
                    "position": 1,
                    "quality": "major"},
 "_M7(add#11/6)-23": {"alteration": "TRUE",
                      "inversion": 0,
                      "notes": [48, 59, 64, 66, 69],
                      "position": 1,
                      "quality": "major"},
 "_M7(add#11/6)-56": {"alteration": "TRUE",
                      "inversion": 0,
                      "notes": [48, 52, 59, 62, 66, 69],
                      "position": 2,
                      "quality": "major"},
 "_M7(add6)-1": {"alteration": "FALSE",
                 "inversion": 0,
                 "notes": [48, 59, 64, 69],
                 "position": 1,
                 "quality": "major"},
 "_M7(add6/9)-3": {"alteration": "FALSE",
                   "inversion": 0,
                   "notes": [48, 59, 64, 69, 74],
                   "position": 1,
                   "quality": "major"},
 "_M7-0": {"alteration": "FALSE",
           "inversion": 0,
           "notes": [48, 59, 64, 67],
           "position": 1,
           "quality": "major"},
 "_M7-39": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 52, 59, 67],
            "position": 2,
            "quality": "major"},
 "_M9(add6)-41": {"alteration": "FALSE",
                  "inversion": 0,
                  "notes": [48, 52, 59, 62, 69],
                  "position": 2,
                  "quality": "major"},
 "_M9(add6)-72": {"alteration": "FALSE",
                  "inversion": 1,
                  "notes": [52, 57, 62, 67, 71],
                  "position": 1,
                  "quality": "major"},
 "_M9(add6)-93": {"alteration": "FALSE",
                  "inversion": 1,
                  "notes": [59, 64, 69, 74, 79],
                  "position": 2,
                  "quality": "major"},
 "_M9-2": {"alteration": "FALSE",
           "inversion": 0,
           "notes": [48, 59, 64, 67, 74],
           "position": 1,
           "quality": "major"},
 "_M9-40": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 52, 59, 62, 67],
            "position": 2,
            "quality": "major"},
 "_dim-102": {"alteration": "FALSE",
              "inversion": 1,
              "notes": [57, 63, 66, 72, 78],
              "position": 2,
              "quality": "diminished"},
 "_dim-113": {"alteration": "TRUE",
              "inversion": 1,
              "notes": [57, 63, 66, 72, 80],
              "position": 2,
              "quality": "diminished"},
 "_dim-21": {"alteration": "FALSE",
             "inversion": 0,
             "notes": [48, 57, 63, 66],
             "position": 1,
             "quality": "diminished"},
 "_dim-37": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 57, 63, 68],
             "position": 1,
             "quality": "diminished"},
 "_dim-38": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 57, 63, 66, 71],
             "position": 1,
             "quality": "diminished"},
 "_dim-54": {"alteration": "FALSE",
             "inversion": 0,
             "notes": [48, 51, 57, 66],
             "position": 2,
             "quality": "diminished"},
 "_dim-70": {"alteration": "TRUE",
             "inversion": 0,
             "notes": [48, 51, 57, 62, 66],
             "position": 2,
             "quality": "diminished"},
 "_dim-80": {"alteration": "FALSE",
             "inversion": 1,
             "notes": [51, 57, 60, 66, 72],
             "position": 1,
             "quality": "diminished"},
 "_dim-92": {"alteration": "TRUE",
             "inversion": 1,
             "notes": [51, 57, 60, 66, 71],
             "position": 1,
             "quality": "diminished"},
 "_m(Maj7)-10": {"alteration": "FALSE",
                 "inversion": 0,
                 "notes": [48, 59, 63, 67],
                 "position": 1,
                 "quality": "minor"},
 "_m(Maj7)-11": {"alteration": "FALSE",
                 "inversion": 0,
                 "notes": [48, 55, 63, 71],
                 "position": 1,
                 "quality": "minor"},
 "_m(Maj7)-44": {"alteration": "FALSE",
                 "inversion": 0,
                 "notes": [48, 51, 59, 67],
                 "position": 2,
                 "quality": "minor"},
 "_m(add9)(Maj7)-12": {"alteration": "FALSE",
                       "inversion": 0,
                       "notes": [48, 59, 63, 67, 74],
                       "position": 1,
                       "quality": "minor"},
 "_m(add9)(Maj7)-45": {"alteration": "FALSE",
                       "inversion": 0,
                       "notes": [48, 51, 59, 62, 67],
                       "position": 2,
                       "quality": "minor"},
 "_m11-16": {"alteration": "FALSE",
             "inversion": 0,
             "notes": [48, 58, 63, 65],
             "position": 1,
             "quality": "minor"},
 "_m11-49": {"alteration": "FALSE",
             "inversion": 0,
             "notes": [48, 51, 58, 62, 65],
             "position": 2,
             "quality": "minor"},
 "_m11-50": {"alteration": "FALSE",
             "inversion": 0,
             "notes": [48, 53, 58, 63, 67],
             "position": 2,
             "quality": "minor"},
 "_m11-77": {"alteration": "FALSE",
             "inversion": 1,
             "notes": [51, 55, 58, 60, 62, 65],
             "position": 1,
             "quality": "minor"},
 "_m11-98": {"alteration": "FALSE",
             "inversion": 1,
             "notes": [58, 63, 67, 72, 77],
             "position": 2,
             "quality": "minor"},
 "_m11♭5-104": {"alteration": "TRUE",
                "inversion": 1,
                "notes": [54, 60, 65, 70, 75],
                "position": 2,
                "quality": "minor"},
 "_m6(Maj7)-74": {"alteration": "FALSE",
                  "inversion": 1,
                  "notes": [51, 57, 62, 67, 71],
                  "position": 1,
                  "quality": "minor"},
 "_m6-6": {"alteration": "FALSE",
           "inversion": 0,
           "notes": [48, 57, 63, 67],
           "position": 1,
           "quality": "minor"},
 "_m6-7": {"alteration": "FALSE",
           "inversion": 0,
           "notes": [48, 55, 63, 69],
           "position": 1,
           "quality": "minor"},
 "_m6/9-43": {"alteration": "FALSE",
              "inversion": 0,
              "notes": [48, 51, 57, 62, 67],
              "position": 2,
              "quality": "minor"},
 "_m6/9-73": {"alteration": "FALSE",
              "inversion": 1,
              "notes": [51, 57, 62, 67, 72],
              "position": 1,
              "quality": "minor"},
 "_m6/9-8": {"alteration": "FALSE",
             "inversion": 0,
             "notes": [48, 55, 63, 69, 74],
             "position": 1,
             "quality": "minor"},
 "_m6/9-9": {"alteration": "FALSE",
             "inversion": 0,
             "notes": [48, 57, 63, 67, 74],
             "position": 1,
             "quality": "minor"},
 "_m7-13": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 58, 63, 67],
            "position": 1,
            "quality": "minor"},
 "_m7-14": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 58, 63, 67, 72],
            "position": 1,
            "quality": "minor"},
 "_m7-46": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 51, 58, 67],
            "position": 2,
            "quality": "minor"},
 "_m7-47": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 51, 58, 60, 67],
            "position": 2,
            "quality": "minor"},
 "_m7-75": {"alteration": "FALSE",
            "inversion": 1,
            "notes": [51, 58, 60, 67, 72],
            "position": 1,
            "quality": "minor"},
 "_m7-96": {"alteration": "FALSE",
            "inversion": 1,
            "notes": [58, 63, 67, 72, 79],
            "position": 2,
            "quality": "minor"},
 "_m7♭5-103": {"alteration": "TRUE",
               "inversion": 1,
               "notes": [54, 60, 63, 70, 75],
               "position": 2,
               "quality": "minor"},
 "_m7♭5-25": {"alteration": "TRUE",
              "inversion": 0,
              "notes": [48, 58, 63, 66],
              "position": 1,
              "quality": "minor"},
 "_m7♭5-26": {"alteration": "TRUE",
              "inversion": 0,
              "notes": [48, 58, 63, 66, 72],
              "position": 1,
              "quality": "minor"},
 "_m7♭5-57": {"alteration": "TRUE",
              "inversion": 0,
              "notes": [48, 51, 58, 66],
              "position": 2,
              "quality": "minor"},
 "_m7♭5-58": {"alteration": "TRUE",
              "inversion": 0,
              "notes": [48, 51, 58, 60, 66],
              "position": 2,
              "quality": "minor"},
 "_m7♭5-81": {"alteration": "TRUE",
              "inversion": 1,
              "notes": [48, 54, 58, 75, 82],
              "position": 1,
              "quality": "minor"},
 "_m9-15": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 58, 63, 67, 74],
            "position": 1,
            "quality": "minor"},
 "_m9-48": {"alteration": "FALSE",
            "inversion": 0,
            "notes": [48, 51, 58, 62, 67],
            "position": 2,
            "quality": "minor"},
 "_m9-76": {"alteration": "FALSE",
            "inversion": 1,
            "notes": [51, 58, 62, 67, 72],
            "position": 1,
            "quality": "minor"},
 "_m9-97": {"alteration": "FALSE",
            "inversion": 1,
            "notes": [58, 63, 67, 74, 79],
            "position": 2,
            "quality": "minor"},
 "_m♭5-82": {"alteration": "TRUE",
             "inversion": 1,
             "notes": [48, 54, 58, 65, 70],
             "position": 1,
             "quality": "minor"},
 "_m6/9(Maj7)-95": {"alteration": "FALSE",
                   "inversion": 1,
                   "notes": [57, 63, 67, 71, 74],
                   "position": 2,
                   "quality": "minor"},
 "_m9(add6)-94": {"alteration": "FALSE",
                 "inversion": 1,
                 "notes": [57, 63, 67, 74, 79],
                 "position": 2,
                 "quality": "minor"}}

